services:
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      -  /usr/local/x-ui:/home
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin@admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/ds.yaml:/etc/grafana/provisioning/datasources/dc.yaml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - loki
    restart: unless-stopped
volumes:
  grafana-storage: