server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: xui-app
    static_configs:
      - targets:
          - "localhost"
        labels:
          job: xui
          __path__: /home/*.log #/usr/local/x-ui/access.log